export const stoks = [
  {
    title: 'Alicia en el pais de las maravillas',
    author: 'J. Lewis',
    editorial: 'El barco de vapor',
    price: 200,
    stock: 300,
    genres: ['fantasia', 'clasicos'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'El nombre del viento',
    author: 'Patrick Rofus',
    editorial: '??',
    price: 300,
    stock: 30,
    genres: ['fantasia', 'medieval'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'Drácula',
    author: 'Bramm Stoker',
    editorial: 'Limusa',
    price: 200,
    stock: 80,
    genres: ['fantasia', 'terror'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'El seductor de la patria',
    author: 'Gustavo Serna',
    editorial: 'Nueva Generacion',
    price: 200,
    stock: 50,
    genres: ['historico', 'novela'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Carmilla',
    author: '??',
    editorial: 'Nueva generacion',
    price: 2000,
    stock: 30,
    genres: ['fantasia', 'terror'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Historia de mi vida',
    author: 'Ivan Cheprakov',
    editorial: 'Fondo Cultural',
    price: 2000,
    stock: 30,
    genres: ['recuentos de la vida', 'historico'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'El retorno de los brujos',
    author: '??',
    editorial: 'Limusa',
    price: 2000,
    stock: 30,
    genres: ['fantasia', 'esoterico'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Alicia en el pais de las maravillas',
    author: 'J. Lewis',
    editorial: 'El barco de vapor',
    price: 200,
    stock: 300,
    genres: ['fantasia', 'clasicos'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'El nombre del viento',
    author: 'Patrick Rofus',
    editorial: '??',
    price: 300,
    stock: 30,
    genres: ['fantasia', 'medieval'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'Drácula',
    author: 'Bramm Stoker',
    editorial: 'Limusa',
    price: 200,
    stock: 80,
    genres: ['fantasia', 'terror'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'El seductor de la patria',
    author: 'Gustavo Serna',
    editorial: 'Nueva Generacion',
    price: 200,
    stock: 50,
    genres: ['historico', 'novela'],
    image: 'http://https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Carmilla',
    author: '??',
    editorial: 'Nueva generacion',
    price: 2000,
    stock: 30,
    genres: ['fantasia', 'terror'],
    image: 'hthttps://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Historia de mi vida',
    author: 'Ivan Cheprakov',
    editorial: 'Fondo Cultural',
    price: 2000,
    stock: 30,
    genres: ['recuentos de la vida', 'historico'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'El retorno de los brujos',
    author: '??',
    editorial: 'Limusa',
    price: 2000,
    stock: 30,
    genres: ['fantasia', 'esoterico'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Alicia en el pais de las maravillas',
    author: 'J. Lewis',
    editorial: 'El barco de vapor',
    price: 200,
    stock: 300,
    genres: ['fantasia', 'clasicos'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'El nombre del viento',
    author: 'Patrick Rofus',
    editorial: '??',
    price: 300,
    stock: 30,
    genres: ['fantasia', 'medieval'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'Drácula',
    author: 'Bramm Stoker',
    editorial: 'Limusa',
    price: 200,
    stock: 80,
    genres: ['fantasia', 'terror'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg',
  },
  {
    title: 'El seductor de la patria',
    author: 'Gustavo Serna',
    editorial: 'Nueva Generacion',
    price: 200,
    stock: 50,
    genres: ['historico', 'novela'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Carmilla',
    author: '??',
    editorial: 'Nueva generacion',
    price: 2000,
    stock: 30,
    genres: ['fantasia', 'terror'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'Historia de mi vida',
    author: 'Ivan Cheprakov',
    editorial: 'Fondo Cultural',
    price: 2000,
    stock: 30,
    genres: ['recuentos de la vida', 'historico'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
  {
    title: 'El retorno de los brujos',
    author: '??',
    editorial: 'Limusa',
    price: 2000,
    stock: 30,
    genres: ['fantasia', 'esoterico'],
    image: 'https://cdni.rt.com/actualidad/public_images/2019.04/article/5caed78ae9180f8a7c8b4567.jpg'
  },
];